run:
  go: "1.20"
  deadline: 20m

linters:
  disable-all: true
  enable:
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused