version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/work
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker: 
          docker_layer_caching: true
      - run:
          name: Make Docker tag
          command: mkdir ./out && echo ${DOCKER_HUB_URL-quay.io}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-$(date -u +"%Y%m%dT%H%M%SZ")-$(echo $CIRCLE_SHA1 | cut -c -7) > ./out/docker_tag && cat ./out/docker_tag
      - run:
          name: Build docker image
          command: docker build -t $(cat ./out/docker_tag) .
      - run:
          name: Save docker image
          command: docker save $(cat ./out/docker_tag) | gzip > ./out/image.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - out
  push:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/work
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker: 
          docker_layer_caching: true
      - run:
          name: Import docker image
          command: 'docker load -i ./out/image.tar.gz'
      - run:
          name: Log into quay
          command: docker login -u ${DOCKER_BOT_USERNAME-cresta+cresta_ci} -p ${DOCKER_BOT_PASSWORD} ${DOCKER_HUB_URL-quay.io}
      - run:
          name: Push docker image
          command: 'docker push $(cat ./out/docker_tag)'
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            branches:
              only: master
