apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitdb.fullname" . }}
  labels:
    {{- include "gitdb.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "gitdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "gitdb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gitdb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.gitdb.envSecrets }}
          envFrom:
            - secretRef:
                name: {{ .Values.gitdb.envSecrets }}
          {{- end }}
          env:
            {{- if .Values.repoConfig }}
            - name: GITDB_REPO_CONFIG
              value: /etc/gitdb_config
            {{- end }}
            {{- if .Values.gitdb.dataDirectory }}
            - name: DATA_DIRECTORY
              value: {{ .Values.gitdb.dataDirectory | quote }}
            {{- end }}
# JWT
            {{- if .Values.jwt.privateKey }}
            - name: GITDB_JWT_PRIVATE_KEY
              value: {{ .Values.jwt.privateKey | quote }}
            {{- end }}
            {{- if .Values.jwt.publicKey }}
            - name: GITDB_JWT_PUBLIC_KEY
              value: {{ .Values.jwt.publicKey | quote }}
            {{- end }}
            {{- if .Values.jwt.signInUsername }}
            - name: GITDB_JWT_SIGNIN_USERNAME
              value: {{ .Values.jwt.signInUsername | quote }}
            {{- end }}

            {{- if .Values.git.privateKey }}
            - name: GITDB_PRIVATE_KEY
              value: {{ .Values.git.privateKey | quote }}
            {{- end }}
            {{- if .Values.git.repos }}
            - name: GITDB_REPOS
              value: {{ .Values.git.repos | quote }}
            {{- end }}
            {{- if .Values.github.pushToken }}
            - name: GITHUB_PUSH_TOKEN
              value: {{ .Values.github.pushToken | quote }}
            {{- end }}
            {{- if .Values.tracer.name }}
            - name: GITDB_TRACER
              value: {{ .Values.tracer.name | quote }}
            {{- end }}
            - name: SSH_KNOWN_HOSTS
              value: /etc/ssh/ssh_known_hosts
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end}}
          volumeMounts:
          {{- if .Values.repoConfig }}
            - mountPath: /etc/gitdb_config
              name: gitdb_config
              readOnly: true
          {{- end }}
          {{- if .Values.git.secretName }}
            - mountPath: /etc/gitdb
              name: git-key
              readOnly: true
          {{- end }}
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.repoConfig }}
      - name: gitdb_config
        configMap:
          name: {{ include "gitdb.fullname" . }}-repos
      {{- end }}
      {{- if .Values.git.secretName }}
      - name: git-key
        secret:
          defaultMode: 256
          secretName: {{ .Values.git.secretName }}
      {{- end }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
